Repository naeggeodo/naeggeodo-web, pull requests merged in 2022-06, with the labels that each got.

#113 채팅방 생성기능 리팩토링 및 기능 추가
  public/assets/images/arrowrightdarkgray.svg
  src/components/create/CreateButton.tsx
  src/components/create/CreateForm.tsx
  src/components/create/CreateInit.tsx
  src/components/create/CreateTabMenu.tsx
  src/components/create/CreateTemplate.tsx
  src/components/create/SelectCategoryDrawer.tsx
  src/components/main/CategoryMenuSlide.tsx
  src/hooks/useCreateNaeggeotalk.ts
  src/modules/create/actions.ts
  src/modules/create/reducer.ts
  src/modules/create/types.ts
  src/pages/create/details/index.tsx
  src/utils/converEngCategoryToKor.ts
Labels: feature

#119 인라인 스타일 수정 및 usecallback 리팩토링
  package.json
  src/components/chatting/ChatItem.tsx
  src/components/chatting/ChattingTemplate.tsx
  src/components/chatting/GoInfoBtn.tsx
  src/components/chatting/Header.tsx
  src/components/chatting/MyChatItem.tsx
  src/components/chatting/QuickMessageComp.tsx
  src/components/chatting/SubmitForm.tsx
  src/components/check-deposit/CheckDepositItem.tsx
  src/components/check-deposit/CheckDepositTemplate.tsx
  src/components/common/Loading.tsx
  src/components/common/stories/Loading.stories.tsx
  src/components/create/CreateInit.tsx
  src/components/create/CreateTabMenu.tsx
  src/components/create/OrderTimeTypeButton.tsx
  src/components/create/SelectCategoryDrawer.tsx
  src/components/login/LoginModalBox.tsx
  src/components/login/LoginModalTemplate.tsx
  src/components/main/TabButtonItem.tsx
  src/components/main/data/index.ts
  src/components/more/stories/MoreTemplate.stories.tsx
  src/components/mypage/MypageTemplate.tsx
  src/components/mypage/stories/MoreTemplate.stories.tsx
  src/components/naeggeotalk/NaeggeotalkTemplate.tsx
  src/components/search/SearchTemplate.tsx
  src/hooks/useSlideTransform.ts
  src/pages/mypage/index.tsx
  src/service/api/check-deposit/CheckDepositService.ts
  yarn.lock
Labels: refactoring

#123 무한스크롤로 교체
  src/components/main/MainTemplate.tsx
  src/hooks/useSlideTransform.ts
Labels: feature

#124 a태그에 noreferrer, noopener 속성 추가
  src/components/login/KaKaoLoginBtn.tsx
  src/components/login/NaverLoginBtn.tsx
  src/components/main/ChatRoomItem.tsx
  src/components/main/TabButtonItem.tsx
  src/hooks/useCheckValidate.ts
Labels: feature

#131 렌딩페이지 디자인 완료
  public/assets/images/applelogo.svg
  public/assets/images/appstore.svg
  public/assets/images/googleplay.png
  src/pages/index.tsx
Labels: feature

#132 rending page 스토리북 추가
  public/.DS_Store
  public/assets/images/googleplay.png
  public/assets/images/googleplay.svg
  src/components/main/stories/RendingPage.stories.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: feature

#133 로그인 기능 수정
  package.json
  src/components/check-deposit/tests/CheckDeposit.test.js
  src/components/create/CreateForm.tsx
  src/components/create/CreateInit.tsx
  src/components/create/CreateTemplate.tsx
  src/components/create/FieldTitle.tsx
  src/components/create/TitleText.tsx
  src/components/login/LoginModalBox.tsx
  src/components/main/CategoryMenuSlide.tsx
  src/components/main/MainTemplate.tsx
  src/components/main/SearchPostCode.tsx
  src/components/main/data/index.ts
  src/components/main/types.ts
  src/components/mypage/CustomerServiceSection.tsx
  src/components/mypage/MypageTemplate.tsx
  src/components/mypage/MypageUserInfo.tsx
  src/components/mypage/Terms.tsx
  src/components/mypage/stories/CustomerService.stories.tsx
  src/components/mypage/stories/MoreTemplate.stories.tsx
  src/components/mypage/stories/MypageUserInfo.stories.tsx
  src/components/mypage/stories/Terms.stories.tsx
  src/components/naeggeotalk/NaeggeotalkTemplate.tsx
  src/components/search/SearchTemplate.tsx
  src/constant/Login.ts
  src/hooks/useCheckValidate.ts
  src/hooks/useKakaoLogin.ts
  src/modules/create/types.ts
  src/modules/index.ts
  src/modules/login/actions.ts
  src/modules/login/reducers.ts
  src/modules/login/sagas.ts
  src/modules/login/types.ts
  src/modules/mypage/actions.ts
  src/modules/mypage/reducer.ts
  src/modules/mypage/sagas.ts
  src/modules/mypage/types.ts
  src/pages/chatRooms/index.tsx
  src/pages/create/details/index.tsx
  src/pages/create/index.tsx
  src/pages/login/OAuth/kakao/index.tsx
  src/pages/login/OAuth/naver/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/service/api/index.ts
  src/service/api/mypage/MypageService.ts
  src/utils/saveCookies.ts
  yarn.lock
Labels: feature, fix

#137 카카오, 네이버 로그인 코드 통합, addr 변수 address 로 수정
  src/components/create/CreateInit.tsx
  src/components/login/LoginModalBox.tsx
  src/constant/Login.ts
  src/hooks/auth/useAuth.ts
  src/hooks/useCheckValidate.ts
  src/hooks/useKakaoLogin.ts
  src/hooks/useNaverLogin.ts
  src/hooks/utils/useLoadLib.ts
  src/modules/login/actions.ts
  src/modules/login/reducers.ts
  src/modules/login/sagas.ts
  src/modules/login/types.ts
  src/pages/_app.tsx
  src/pages/chatRooms/index.tsx
  src/pages/login/OAuth/kakao/index.tsx
  src/pages/login/OAuth/naver/index.tsx
  src/pages/login/index.tsx
  src/utils/saveCookies.ts
Labels: refactoring

#140 address, user_id 로 변수명 변경 완료
  src/components/main/SearchPostCode.tsx
  src/components/mypage/FeedbackForm.tsx
  src/modules/chatting/types.ts
  src/modules/create/reducer.ts
  src/modules/create/types.ts
  src/modules/login/actions.ts
  src/modules/login/reducers.ts
  src/modules/login/sagas.ts
  src/modules/login/types.ts
  src/utils/saveCookies.ts
Labels: fix

#141 axios instace 클라이언트 사이드용 새로 생성
  src/components/main/MainTemplate.tsx
  src/hooks/auth/useLoadLoginStates.ts
  src/modules/search-post-code/reducer.ts
  src/modules/search-post-code/types.ts
  src/pages/mypage/index.tsx
  src/pages/naeggeotalk/index.tsx
  src/pages/search/index.tsx
  src/service/api/index.ts
  src/utils/createCustomHeader.ts
Labels: refactoring

#142 infinite scroll 훅으로 수정
  src/components/main/MainTemplate.tsx
  src/constant/Login.ts
  src/hooks/reder/useInfiniteScroll.ts
Labels: refactoring

#143 axios instance 설정 코드 함수로 분리
  src/pages/chatRooms/index.tsx
  src/service/api/index.ts
Labels: refactoring

#145 refactor : CSR 전용 API코드로 수정
  src/components/check-deposit/CompleteDepositButton.tsx
  src/components/naeggeotalk/NaeggeotalkTemplate.tsx
  src/components/search/SearchResultList.tsx
  src/components/search/SearchTemplate.tsx
  src/modules/search/sagas.ts
  src/pages/chatting/[id].tsx
  src/pages/check-deposit/[id].tsx
  src/service/api/check-deposit/CheckDepositService.ts
  src/service/api/index.ts
  src/service/api/mypage/MypageService.ts
  src/service/api/naeggeotalk/NaeggeotalkService.ts
  src/service/api/search-post-code/SearchPostCodeService.ts
  src/service/api/search/SearchService.ts
Labels: refactoring

#146 chore : userId를 user_id로 변경
  src/components/mypage/ComplainForm.tsx
  src/components/mypage/MypageTemplate.tsx
  src/components/naeggeotalk/NaeggeotalkListItem.tsx
  src/components/search/stories/SearchTemplate.stories.tsx
  src/modules/naeggeotalk/types.ts
  src/utils/DateFormatter.ts
Labels: chore

#147 fix : 채팅방 아이디, 유저 아이디 수정
  src/components/chatting/ChattingTemplate.tsx
  src/components/chatting/QuickMessageComp.tsx
  src/components/chatting/SubmitForm.tsx
  src/hooks/useChat.ts
  src/modules/chatting/types.ts
Labels: fix

#148 메인페이지 스크롤 부분 수정
  src/components/main/MainTemplate.tsx
  src/hooks/useCheckValidate.ts
  src/modules/login/actions.ts
  src/modules/login/reducers.ts
  src/modules/search-post-code/reducer.ts
  src/modules/search-post-code/sagas.ts
  src/pages/chatRooms/index.tsx
Labels: refactoring

#150 서버사이드 렌더링으로 회원정보 불러오기 완료
  src/components/mypage/MypageTemplate.tsx
  src/modules/mypage/sagas.ts
  src/pages/mypage/index.tsx
Labels: fix

#152 orderTimeType 렌더링 기능 추가 & useInifiniteScroll 타입지정 추가
  src/components/main/ChatRoomItem.tsx
  src/components/main/ChatRoomList.tsx
  src/hooks/reder/useInfiniteScroll.ts
  src/modules/create/types.ts
  src/modules/main/types.ts
  src/pages/_app.tsx
  src/pages/chatting/[id].tsx
  src/pages/check-deposit/[id].tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/naeggeotalk/index.tsx
  src/pages/search/index.tsx
  src/service/api/index.ts
  src/utils/convertOrderTimeType.ts
Labels: feature, refactoring

#153 검색 페이지 데이터 수정 완료
  src/components/search/SearchResultList.tsx
  src/components/search/SearchTemplate.tsx
  src/modules/main/types.ts
  src/modules/search/types.ts
Labels: feature

#155 chore : 채팅 생성 부분 페이지, url 수정
  src/components/create/CreateInit.tsx
  src/components/create/CreateTemplate.tsx
  src/components/naeggeotalk/NaeggeotalkListItem.tsx
  src/components/search/SearchTemplate.tsx
  src/modules/create/reducer.ts
  src/modules/search/sagas.ts
  src/pages/create/details/index.tsx
  src/pages/create/index.tsx
Labels: chore

#156 refactor : 채팅방 리스트 컴포넌트로 분리
  src/components/chatting/ChatDrawer.tsx
  src/components/chatting/ChattingList.tsx
  src/components/chatting/ChattingTemplate.tsx
  src/components/create/CreateInit.tsx
Labels: refactoring

#158 수정안된부분 마무리 수정
  src/components/search/SearchTemplate.tsx
Labels: refactoring

#160 chore : 채팅생성 컴포넌트 폴더 만들음
  src/components/create/CreateInit.tsx
  src/components/create/CreateTemplate.tsx
  src/components/create/PrevCreatedItem.tsx
  src/components/create/PrevCreatedList.tsx
  src/components/create/createForm/CreateDetails.tsx
  src/components/create/createForm/CreateForm.tsx
  src/components/create/createForm/FieldTitle.tsx
  src/components/create/createForm/SelectCategoryDrawer.tsx
  src/components/create/createForm/TagButton.tsx
  src/components/create/createForm/TitleText.tsx
  src/components/create/stories/CreateForm.stories.tsx
  src/components/create/stories/SelectCategoryStories.stories.tsx
  src/components/create/stories/TagButton.stories.tsx
  src/modules/create/sagas.ts
  src/modules/naeggeotalk/types.ts
  src/service/api/create/CreateService.ts
Labels: chore

#161 fix : userid 값수정
  src/hooks/useChat.ts
Labels: chore

#163 이미지 렌더링 수정
  next.config.js
  package.json
  src/components/chatting/ChattingTemplate.tsx
  src/components/chatting/Header.tsx
  src/components/common/AppLayout.tsx
  src/components/create/CreateButton.tsx
  src/components/create/CreateInit.tsx
  src/components/create/CreateTabMenu.tsx
  src/components/create/CreateTemplate.tsx
  src/components/create/PrevCreatedItem.tsx
  src/components/create/PrevCreatedList.tsx
  src/components/create/createForm/CreateForm.tsx
  src/components/main/ChatRoomItem.tsx
  src/components/main/ChatRoomList.tsx
  src/components/main/MainTemplate.tsx
  src/components/search/SearchResultList.tsx
  src/components/search/SearchTemplate.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/useCreateNaeggeotalk.ts
  src/modules/chatting/types.ts
  src/modules/create/actions.ts
  src/modules/create/reducer.ts
  src/modules/create/types.ts
  src/modules/login/actions.ts
  src/modules/login/reducers.ts
  src/modules/login/sagas.ts
  src/modules/login/types.ts
  src/modules/main/types.ts
  src/modules/search-post-code/sagas.ts
  src/modules/search/reducer.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/chatting/[id].tsx
  src/pages/create/index.tsx
  src/service/api/create/CreateService.ts
  src/service/api/naeggeotalk/NaeggeotalkService.ts
  src/service/api/search/SearchService.ts
  src/utils/converEngCategoryToKor.ts
  src/utils/saveCookies.ts
  yarn.lock
Labels: fix

#164 메인페이지 리팩토링 및 기능 완성
  src/components/common/CompleteModalBox.tsx
  src/components/common/CompleteModalTemplate.tsx
  src/components/create/CreateTemplate.tsx
  src/components/create/createForm/CreateForm.tsx
  src/components/main/CategoryMenuSlide.tsx
  src/components/main/ChatRoomList.tsx
  src/components/search/CurrentLocation.tsx
  src/components/search/SearchResultList.tsx
  src/components/search/SearchTemplate.tsx
  src/hooks/render/useInfiniteScroll.ts
  src/hooks/select/useSelectLoginStates.ts
  src/hooks/useCreateNaeggeotalk.ts
  src/modules/modal/actions.ts
  src/modules/modal/reducer.ts
  src/modules/modal/types.ts
  src/pages/chat-rooms/index.tsx
  src/pages/index.tsx
Labels: fix, refactoring

#165 로그인 이슈 해결 & 스토리북 에러 이슈 해결
  src/components/chatting/GoInfoBtn.tsx
  src/components/chatting/Header.tsx
  src/components/chatting/SubmitForm.tsx
  src/components/chatting/stories/GoInfoBtn.stories.tsx
  src/components/chatting/stories/Header.stories.tsx
  src/components/chatting/stories/SubmitForm.stories.tsx
  src/components/check-deposit/CheckDepositTemplate.tsx
  src/components/common/CompleteModalBox.tsx
  src/components/create/createForm/CreateForm.tsx
  src/components/create/stories/CreateForm.stories.tsx
  src/components/create/stories/CreateTemplate.stories.tsx
  src/components/login/LoginTemplate.tsx
  src/components/main/data/index.ts
  src/components/main/stories/RendingPage.stories.tsx
  src/components/mypage/stories/ComplainForm.stories.tsx
  src/components/mypage/stories/CustomerService.stories.tsx
  src/components/mypage/stories/FeedbakForm.stories.tsx
  src/components/mypage/stories/MoreTemplate.stories.tsx
  src/components/mypage/stories/MypageUserInfo.stories.tsx
  src/components/mypage/stories/Terms.stories.tsx
  src/components/naeggeotalk/stories/NaeggeotalkListItem.stories.tsx
  src/components/search/CurrentLocation.tsx
  src/components/search/SearchTag.tsx
  src/components/search/SearchTemplate.tsx
  src/components/search/stories/SearchTag.stories.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/search/useSearchChatRoom.ts
  src/hooks/select/useSelectLoginStates.ts
  src/hooks/utils/useCustomRouter.ts
  src/modules/login/sagas.ts
  src/modules/search/reducer.ts
  src/modules/search/sagas.ts
  src/pages/create/index.tsx
  src/pages/login/OAuth/kakao/index.tsx
  src/pages/login/index.tsx
  src/service/api/index.ts
  src/service/api/login/LoginService.ts
  src/utils/filterLocation.ts
Labels: feature, fix, refactoring

#167 chat-room fix 브랜치 머지 및 내꺼톡 생성
  src/components/chatting/ChatDrawer.tsx
  src/components/chatting/ChatItem.tsx
  src/components/chatting/ChattingList.tsx
  src/components/chatting/ChattingTemplate.tsx
  src/components/chatting/MyChatItem.tsx
  src/components/chatting/QuickMessageComp.tsx
  src/components/check-deposit/CheckDepositTemplate.tsx
  src/components/check-deposit/ConvertToCompletedButton.tsx
  src/components/mypage/MypageTemplate.tsx
  src/components/progress/ProgressTemplate.tsx
  src/hooks/useChat.ts
  src/modules/chatting/sagas.ts
  src/modules/chatting/types.ts
  src/modules/check-deposit/sagas.ts
  src/modules/naeggeotalk/types.ts
  src/pages/chatting/[id].tsx
  src/pages/check-deposit/[id].tsx
  src/pages/progress/index.tsx
  src/service/api/chatting/ChattingService.ts
  src/service/api/check-deposit/CheckDepositService.ts
Labels: feature, fix, refactoring

#168 fix : 무한스크롤 수정
  .storybook/preview.js
  package.json
  src/components/chatting/ChatDrawer.tsx
  src/components/chatting/ChattingList.tsx
  src/components/chatting/ChattingTemplate.tsx
  src/components/chatting/Header.tsx
  src/components/chatting/stories/ChatDrawer.stories.tsx
  src/components/chatting/stories/ChattingTemplate.stories.tsx
  src/components/chatting/stories/Header.stories.tsx
  src/components/chatting/stories/QuickMessageComp.stories.tsx
  src/components/chatting/stories/SubmitForm.stories.tsx
  src/components/check-deposit/ConvertToCompletedButton.tsx
  src/components/check-deposit/stories/CheckDepositItem.stories.tsx
  src/components/check-deposit/stories/CompleteDepositButton.stories.tsx
  src/components/check-deposit/stories/ConvertToCompleteButton.stories.tsx
  src/components/create/PrevCreatedList.tsx
  src/components/main/ChatRoomList.tsx
  src/components/naeggeotalk/NaeggeotalkListItem.tsx
  src/hooks/render/useInfiniteScroll.ts
  src/hooks/useChat.ts
  src/modules/chatting/types.ts
  src/pages/chatting/[id].tsx
  yarn.lock
Labels: fix

#169 refactor : 건의하기/신고하기 ui를 모달창으로 변경
  src/components/common/Popup.tsx
  src/components/mypage/ComplainForm.tsx
  src/components/mypage/CustomerServiceSection.tsx
  src/components/mypage/FeedbackForm.tsx
  src/components/mypage/MypageTemplate.tsx
  src/components/mypage/report/ComplainForm.tsx
  src/components/mypage/report/CompleteAlertModal.tsx
  src/components/mypage/report/ConfirmModal.tsx
  src/components/mypage/report/ConfirmModalTemplate.tsx
  src/components/mypage/report/ControllButtons.tsx
  src/components/mypage/report/FeedbackForm.tsx
  src/components/mypage/report/ReportModalTemplate.tsx
  src/components/mypage/stories/ComplainForm.stories.tsx
  src/components/mypage/stories/FeedbakForm.stories.tsx
  src/hooks/useReport.ts
  src/modules/mypage/actions.ts
  src/modules/mypage/reducer.ts
  src/pages/_document.tsx
Labels: refactoring

#170 참여중인 톡방 제목 변경기능
  public/assets/images/pencilicon.svg
  src/components/main/data/index.ts
  src/components/progress/ProgressTalkItem.tsx
  src/components/progress/ProgressTemplate.tsx
  src/modules/index.ts
  src/modules/progress/actions.ts
  src/modules/progress/reducer.ts
  src/modules/progress/sagas.ts
  src/modules/progress/types.ts
  src/pages/progress/index.tsx
  src/service/api/progress/ProgressService.ts
Labels: feature

#173 접근성 이슈 일부 수정
  src/components/main/CategoryMenuSlide.tsx
  src/components/main/ChatRoomItem.tsx
  src/components/progress/ProgressTalkItem.tsx
  src/components/search/CurrentLocation.tsx
  src/components/search/SearchResultList.tsx
  src/pages/_document.tsx
  src/pages/chatting/[id].tsx
Labels: feature

#182 config : ssl 설정
  .DS_Store
  .gitignore
  package.json
  server.js
Labels: config
